### Request Code for Verification using email
POST http://localhost:3000/api/auth/register/request-code
Content-Type: application/json

{
  "identifier": "regysaputra27@gmail.com",
  "channel": "email"
}

### Request Code for Verification using sms
POST http://localhost:3000/api/auth/register/request-code
Content-Type: application/json

{
  "identifier": "+62895326130662",
  "channel": "sms"
}

### Verify Code
POST http://localhost:3000/api/auth/register/verify-code
Content-Type: application/json

{
  "code": "182248",
  "identifier": "regysaputradev@gmail.com"
}

### Register User
POST http://localhost:3000/api/auth/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWVyIjoicmVneXNhcHV0cmFkZXZAZ21haWwuY29tIiwiaWF0IjoxNzczMzgwNDU3LCJleHAiOjE3NzMzODIyNTd9.OshtSjDirwlQoA0kjfQF1cfL2gqNie-b0rzNp3M3VqY
X-Forwarded-For: 114.10.148.4
Content-Type: application/json

{
  "name": "Regy Saputra",
  "password": "12345678"
}

### Login User
POST http://localhost:3000/api/auth/login
X-Forwarded-For: 114.10.148.4
Content-Type: application/json

{
  "email": "regysaputradev@gmail.com",
  "password": "12345678",
  "rememberMe": false
}

> {%
  // Log all response headers to see if Set-Cookie exists
  console.log("All response headers:", response.headers);
  console.log("Set-Cookie header:", response.headers["set-cookie"]);

  // Check specifically for refresh_token cookie
  const setCookie = response.headers["set-cookie"];
  if (setCookie) {
    console.log("Cookies being set:", setCookie);
    if (setCookie.some(c => c.includes("refresh_token"))) {
      console.log("✓ Refresh token cookie found!");
    } else {
      console.log("✗ No refresh_token cookie in Set-Cookie");
    }
  } else {
    console.log("✗ No Set-Cookie headers in response");
  }
%}

### Debug
GET http://localhost:3000/api/debug-cookies

### Refresh Session
POST http://localhost:3000/api/auth/refresh
X-Forwarded-For: 114.10.148.4

### Get User Profile
GET http://localhost:3000/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTlkMGI1Zi04NDdmLTc0YWItYmJmNC03YjI5YTcxYWRiOWIiLCJpYXQiOjE3NzQwMTIzMDIsImV4cCI6MTc3NDAxNDEwMn0.mgdkaihN0MgWEN_5LjsqrOelmNGSoIJ5shb5ETXuyjU

### Get All Thread
GET http://localhost:3000/api/threads/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMTlkMGI1Zi04NDdmLTc0YWItYmJmNC03YjI5YTcxYWRiOWIiLCJpYXQiOjE3NzQwMTIzMDIsImV4cCI6MTc3NDAxNDEwMn0.mgdkaihN0MgWEN_5LjsqrOelmNGSoIJ5shb5ETXuyjU
