name: Continuous Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "Starting deployment..."
            cd ~/devforum-backend || exit 1
            git pull origin main
            /usr/bin/npm install
            /usr/bin/npm ci --omit=dev --no-audit --no-fund
            /usr/bin/npm run migrate up
            /usr/bin/pm2 restart all
          debug: true
